
---
development:
  cloud_name: noamesu
  api_key: '286647342461698'
  api_secret: jX9d9_VwEtfU7c7cTWntQgM2E_Q
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: noamesu
  api_key: '286647342461698'
  api_secret: jX9d9_VwEtfU7c7cTWntQgM2E_Q
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: noamesu
  api_key: '286647342461698'
  api_secret: jX9d9_VwEtfU7c7cTWntQgM2E_Q
  enhance_image_tag: true
  static_file_support: false
